---
title: "5dpf"
author: "LR"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r colours}
A.col1 <- 
  scale_fill_viridis_d(option = "mako",
                       begin = .85,
                       end = .45)
A.col2 <-
  scale_color_viridis_d(option = "mako",
                        begin = .85,
                        end = .45)


B.col1 <- 
  scale_fill_viridis_d(option = "inferno",
                       begin = 0.88,
                       end = .6) 
B.col2 <-
  scale_colour_viridis_d(option = "inferno",
                         begin = 0.88,
                         end = .6)


C.col1 <-
  scale_fill_viridis_d(option = "magma",
                       end = 0.18, begin = .6) 
C.col2 <-
  scale_colour_viridis_d(option = "magma",
                         end = 0.18, begin = 0.6) 
```


```{r A legend}

A.5.legtrial <-
  A.5.totaldist %>%
  
  ggplot(aes(x = Genotype, y = Total_distance)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  guides(colour = "none") +
  scale_shape_manual(values= c(16,17,15,3,7,8,13),
                     guide = guide_legend(nrow = 1)) +
  theme(legend.position = "top") +
  labs(color = "Genotype", shape = "Trial") +
  scale_colour_discrete(guide = FALSE) +
  scale_fill_discrete(guide = FALSE) 



A.5.legtrial

```



```{r making models distance travelled}


#A model----

#model is singular for TRIAL which is fine
A.5.model.totaldistance <- 
  A.5.totaldist %>%
  droplevels() %>%
  lmer(formula = sqrt(Total_distance) ~ Genotype + (1|Trial))

plot(residuals(A.5.model.totaldistance) ~ fitted(A.5.model.totaldistance)) 
qqPlot(residuals(A.5.model.totaldistance))


Anova(A.5.model.totaldistance) %>%
  as.data.frame() %>%
  dplyr::rename(pval = `Pr(>Chisq)`) %>%
  kable(caption = "Type II Wald chisquare test of LME") %>%
  kable_styling()


#B model-----------
B.5.model.totaldistance <- B.5.totaldist %>%
  droplevels() %>%
  lmer(formula = log(Total_distance) ~ Genotype + (1|Trial))

plot(residuals(B.5.model.totaldistance) ~ fitted(B.5.model.totaldistance)) 
qqPlot(residuals(B.5.model.totaldistance))

Anova(B.5.model.totaldistance) %>%
  as.data.frame() %>%
  dplyr::rename(pval = `Pr(>Chisq)`) %>%
  kable(caption = "Type II Wald chisquare test of LME") %>%
  kable_styling()


#C model----
C.5.model.totaldistance <- C.5.totaldist %>%
  droplevels() %>%
  lmer(formula = sqrt(Total_distance) ~ Genotype + (1|Trial))

plot(residuals(C.5.model.totaldistance) ~ fitted(C.5.model.totaldistance)) 
qqPlot(residuals(C.5.model.totaldistance))

Anova(C.5.model.totaldistance) %>%
  as.data.frame() %>%
  dplyr::rename(pval = `Pr(>Chisq)`) %>%
  kable(caption = "Type II Wald chisquare test of LME") %>%
  kable_styling()


```


```{r binned emeans STATS}

#is singular around the effect of trial 
A.5.model.20minbin <- A.5.fulldata %>%  
  mutate(fish_id = as.character(fish_id)) %>% 
  droplevels() %>%
  lmer(formula = sqrt(Distance_travelled) ~ (Bin*Genotype) + (1|Trial) + (1|fish_id),
       data = .)


plot(residuals(A.5.model.20minbin) ~ fitted(A.5.model.20minbin)) 
qqPlot(residuals(A.5.model.20minbin))


Anova(A.5.model.20minbin) %>%
  as.data.frame() %>%
  dplyr::rename(pval = `Pr(>Chisq)`) %>%
  kable(caption = "Type II Wald chisquare test of LME") %>%
  kable_styling()



B.5.model.20minbin <- B.5.fulldata %>%  
  mutate(fish_id = as.character(fish_id)) %>% 
  droplevels() %>%
  lmer(formula = log(Distance_travelled) ~ (Bin*Genotype) + (1|Trial) + (1|fish_id),
       data = .) #,
#family = Gamma (link = "log"))

plot(residuals(B.5.model.20minbin) ~ fitted(B.5.model.20minbin)) 
qqPlot(residuals(B.5.model.20minbin))



Anova(B.5.model.20minbin) %>%
  as.data.frame() %>%
  dplyr::rename(pval = `Pr(>Chisq)`) %>%
  kable(caption = "Type II Wald chisquare test of LME") %>%
  kable_styling()



C.5.model.20minbin <- C.5.fulldata %>%  
  mutate(fish_id = as.character(fish_id)) %>% 
  droplevels() %>%
  lmer(formula = Distance_travelled ~ (Bin*Genotype) + (1|Trial) + (1|fish_id),
       data = .)


plot(residuals(C.5.model.totaldistance) ~ fitted(C.5.model.totaldistance)) 
qqPlot(residuals(C.5.model.totaldistance))


Anova(C.5.model.20minbin) %>%
  as.data.frame() %>%
  dplyr::rename(pval = `Pr(>Chisq)`) %>%
  kable(caption = "Type II Wald chisquare test of LME") %>%
  kable_styling()





```


```{r centre time spent STATS1}


A.5.lm_time_centre1 <-
  A.5.fulldata %>%
  group_by(fish_id) %>%
  dplyr::mutate(Time_in_centre = replace(Time_in_centre, Time_in_centre == 0, 0.0000001)) %>%
  glmmTMB(formula = Time_in_centre/1200 ~ (Genotype*Bin) + (1|Trial) + (1|fish_id), 
          data = .,
          family = beta_family(link = "logit"))


plot(residuals(A.5.lm_time_centre1) ~ fitted(A.5.lm_time_centre1)) 
qqPlot(residuals(A.5.lm_time_centre1))


Anova(A.5.lm_time_centre1)



B.5.lm_time_centre1 <-
  B.5.fulldata %>%
  group_by(fish_id) %>%
  dplyr::mutate(Time_in_centre = replace(Time_in_centre, Time_in_centre == 0, 0.0000001)) %>%
  glmmTMB(formula = Time_in_centre/1200 ~ Genotype + Bin + (1|Trial) + (1|fish_id), 
          data = .,
          family = beta_family(link = "logit"))

Anova(B.5.lm_time_centre1)






C.5.lm_time_centre1 <-
  C.5.fulldata %>%
  group_by(fish_id) %>%
  dplyr::mutate(Time_in_centre = replace(Time_in_centre, Time_in_centre == 0, 0.0000001)) %>%
  glmmTMB(formula = Time_in_centre/1200 ~ (Genotype*Bin) + (1|Trial) + (1|fish_id), 
          data = .,
          family = beta_family(link = "logit"))

Anova(C.5.lm_time_centre1)


```



```{r frequency models}
A.5.lm.freq <-
  A.5.fulldata %>% 
  dplyr::mutate(fish_id = as.character(fish_id)) %>% 
  glmer.nb(Freq_in_centre ~ Bin + Genotype + (1|Trial) + (1|fish_id),
           data = .,
           family = Poisson (link = "log"))


Anova(A.5.lm.freq)



B.5.lm.freq <-
  B.5.fulldata %>% 
  dplyr::mutate(fish_id = as.character(fish_id)) %>% 
  glmer.nb(Freq_in_centre ~ Bin+Genotype + (1|Trial) + (1|fish_id),
           data = .,
           family = Poisson (link = "log"))


Anova(B.5.lm.freq)



C.5.lm.freq <-
  C.5.fulldata %>% 
  dplyr::mutate(fish_id = as.character(fish_id)) %>% 
  glmer.nb(Freq_in_centre ~ (Bin*Genotype) + (1|Trial) + (1|fish_id),
           data = .,
           family = Poisson (link = "log"))


Anova(C.5.lm.freq)

```


