---
title: "Raw All"
author: "LR"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Making raw data plots for all families

```{r legend}

B.legtrial <-
  B.5.totaldist %>%
  
  ggplot(aes(x = Genotype, y = Total_distance)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  scale_fill_viridis_d(option = "viridis",
                       begin = 0.5,
                       end = 1) +
  scale_colour_viridis_d(option = "viridis",
                         begin = 0.5,
                         end = 1) +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
  scale_x_discrete(name = "MPS IIIA") +
  theme(legend.position = "top") +
  labs(color = "Genotype", shape = "Trial") +
  scale_colour_discrete(guide = FALSE) +
  scale_fill_discrete(guide = FALSE) 


C.legtrial <-
  C.5.totaldist %>%
  
  ggplot(aes(x = Genotype, y = Total_distance)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  scale_fill_viridis_d(option = "viridis",
                       begin = 0.5,
                       end = 1) +
  scale_colour_viridis_d(option = "viridis",
                         begin = 0.5,
                         end = 1) +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
  scale_x_discrete(name = "MPS IIIA") +
  theme(legend.position = "top") +
  labs(color = "Genotype", shape = "Trial") +
  scale_colour_discrete(guide = FALSE) +
  scale_fill_discrete(guide = FALSE) 




```

```{r total distant for mps iiib only}
cowplot::plot_grid(
  cowplot::plot_grid(
    
  
    p.B.5.totaldist + 
      scale_y_continuous(labels = comma, name = "Distance (mm)",
                         limits = c(0,29000)) +
      scale_x_discrete(name = element_blank()),
    
    p.B.7.totaldist + 
      scale_y_continuous(labels = comma, name = element_blank(), 
                         limits = c(0,29000)) + 
      scale_x_discrete(name = element_blank()),
    
    p.B.14.totaldist + 
      scale_y_continuous(labels = comma, name = element_blank(),
                         limits = c(0,29000))+ 
      scale_x_discrete(name = element_blank()),
    
    
    align = "v",
    ncol = 3,
    labels = "AUTO"
  ),
  cowplot::get_legend(
    B.legtrial + scale_colour_discrete(guide = FALSE) +
      scale_fill_discrete(guide = FALSE) +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal",
        text = element_text(size = 15))
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Total distance/mpsiiib.png", width = 30, height = 15, units = "cm", dpi = 400, scale = .8)


```



```{r Total dist}

p.A.5.totaldist <-
A.5.totaldist %>%
  
  ggplot(aes(x = Genotype, y = Total_distance)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
  scale_x_discrete(name = "MPS IIIA") +
  theme(legend.position = "none") +
  theme(text = element_text(size = 12), 
        axis.title.x = element_text(face="bold"))


p.A.7.totaldist <-
A.7.totaldist %>%
  
  ggplot(aes(x = Genotype, y = Total_distance)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
    A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = element_blank()) +
  scale_x_discrete(name = "MPS IIIB") +
  theme(legend.position = "none")


p.A.14.totaldist <-
A.14.totaldist %>%
  ggplot(aes(x = Genotype, y = Total_distance)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = element_blank()) +
  scale_x_discrete(name = element_blank()) +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 
  
#---- B


p.B.5.totaldist <-
B.5.totaldist %>%
  
  ggplot(aes(x = Genotype, y = Total_distance)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
    B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = element_blank()) 

p.B.7.totaldist <-
B.7.totaldist %>%
  
  ggplot(aes(x = Genotype, y = Total_distance)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
    B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = element_blank())


p.B.14.totaldist <-
B.14.totaldist %>%
  ggplot(aes(x = Genotype, y = Total_distance)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
    B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = element_blank())









cowplot::plot_grid(
  cowplot::plot_grid(
    
    p.A.5.totaldist +
      scale_y_continuous(labels = comma, name = "Distance (mm)",
                         limits = c(0,39000)) +
      scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
      scale_x_discrete(name = " ") +
      ggtitle("MPS IIIA 5 dpf") +
      theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)),
    
    p.A.7.totaldist + 
      scale_y_continuous(labels = comma, name = element_blank(),
                         limits = c(0,39000)) +
      scale_x_discrete(name = " ") +
      ggtitle("MPS IIIA 7 dpf") +
      theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)),
    
    p.A.14.totaldist + 
      scale_y_continuous(labels = comma, name = element_blank(),
                         limits = c(0,39000)) +
      scale_x_discrete(name = " ") +
      ggtitle("MPS IIIA 14 dpf") +
      theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)),
        align = "h",
    ncol = 3,
    labels = "AUTO"
  ),
  cowplot::get_legend(
    A.5.legtrial + scale_colour_discrete(guide = FALSE) +
      scale_fill_discrete(guide = FALSE) +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal",
        text = element_text(size = 15))
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1))

ggsave(filename = "Raw data/Total distance/ MPS IIIA total distance.png", width = 30, height = 25, units = "cm", dpi = 400, scale = .6)

    


cowplot::plot_grid(
  cowplot::plot_grid(

    p.B.5.totaldist + 
      scale_y_continuous(labels = comma, name = "Distance (mm)",
                         limits = c(0,29000)) +
      scale_x_discrete(name = " ", labels=c("wt" = "+/+", "het" = "+/A603Efs", "hom" = "A603Efs/A603Efs")) +
      ggtitle("MPS IIIB 5 dpf") +
      theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1), legend.position = "none"),
  
    p.B.7.totaldist + 
      scale_y_continuous(labels = comma, name = element_blank(), 
                         limits = c(0,29000)) + 
      scale_x_discrete(name = " ", labels=c("wt" = "+/+", "het" = "+/A603Efs", "hom" = "A603Efs/A603Efs")) +
      ggtitle("MPS IIIB 7 dpf") +
      theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1), legend.position = "none"),
    
    p.B.14.totaldist + 
      scale_y_continuous(labels = comma, name = element_blank(),
                         limits = c(0,29000))+ 
      scale_x_discrete(name = " ", labels=c("wt" = "+/+", "het" = "+/A603Efs", "hom" = "A603Efs/A603Efs")) +
      ggtitle("MPS IIIB 14 dpf") +
      theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1), legend.position = "none"),
    align = "h",
    ncol = 3,
    labels = "AUTO"
  ),
  cowplot::get_legend(
    B.legtrial + scale_colour_discrete(guide = FALSE) +
      scale_fill_discrete(guide = FALSE) +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal",
        text = element_text(size = 15))
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Total distance/ B total distance.png", width = 30, height = 25, units = "cm", dpi = 400, scale = .6)



cowplot::plot_grid(
  cowplot::plot_grid(

    p.C.5.totaldist +
      scale_y_continuous(labels = comma, name = "Distance (mm)",
                         limits = c(0,37000))+ 
        scale_x_discrete(name = " ", labels=c("wt" = "+/+", "het" = "+/G557fs", "hom" = "G557fs/G557fs")) +
      ggtitle("MPS IIIC 5 dpf") +
      theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1), legend.position = "none"),
    
    p.C.7.totaldist +
      scale_y_continuous(labels = comma, name = element_blank(),
                         limits = c(0,37000))+ 
        scale_x_discrete(name = " ", labels=c("wt" = "+/+", "het" = "+/G557fs", "hom" = "G557fs/G557fs")) +
      ggtitle("MPS IIIC 7 dpf") +
      theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1), legend.position = "none"),
    
    
    p.C.14.totaldist +
      scale_y_continuous(labels = comma, name = element_blank(),
                         limits = c(0,37000))+ 
         scale_x_discrete(name = " ", labels=c("wt" = "+/+", "het" = "+/G557fs", "hom" = "G557fs/G557fs")) +
      ggtitle("MPS IIIC 14 dpf") +
      theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1), legend.position = "none"),
    
    align = "h",
    ncol = 3,
    labels = "AUTO"
  ),
  cowplot::get_legend(
    C.legtrial + scale_colour_discrete(guide = FALSE) +
      scale_fill_discrete(guide = FALSE) +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal",
        text = element_text(size = 15))
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Total distance/c total distance.png", width = 30, height = 25, units = "cm", dpi = 400, scale = .6)



```

```{r effect of trial}

Trial.A <-
  A.14.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits = c(0,40000)) +
  theme(text = element_text(size = 15))


Trial.B <-
  B.14.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits = c(0,40000)) +
  theme(text = element_text(size = 15))


Trial.C <-
  C.14.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits = c(0,40000)) +
  theme(text = element_text(size = 15))



ggarrange(Trial.A + theme(legend.position = "none"), 
          ggarrange(Trial.B, Trial.C + scale_y_continuous(labels = comma, name = element_blank()),
                    ncol = 2, 
                    common.legend = TRUE,
                    legend = "bottom"
          ),
          nrow = 2)


ggsave(filename = "TRIAL MPSIII 14.png", width = 30, height = 20, units = "cm", dpi = 400, scale = 0.7)


```


```{r trial effect for supplementary}
A.5.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
  theme(legend.position = "bottom")

ggsave(filename = "Raw data/Trial/A.5.png", width = 30, height = 30, units = "cm", dpi = 400, scale = 0.6)

A.7.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
  theme(legend.position = "bottom")

ggsave(filename = "Raw data/Trial/A.7.png", width = 30, height = 30, units = "cm", dpi = 400, scale = 0.6)

A.14.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
  theme(legend.position = "bottom")

ggsave(filename = "Raw data/Trial/A.14.png", width = 30, height = 30, units = "cm", dpi = 400, scale = 0.6)


B.5.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
  theme(legend.position = "bottom")

ggsave(filename = "Raw data/Trial/B.5.png", width = 30, height = 30, units = "cm", dpi = 400, scale = 0.6)


B.7.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
    theme(legend.position = "bottom")


ggsave(filename = "Raw data/Trial/B.7.png", width = 30, height = 30, units = "cm", dpi = 400, scale = 0.6)


B.14.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
  theme(legend.position = "bottom")

ggsave(filename = "Raw data/Trial/B.14.png", width = 30, height = 30, units = "cm", dpi = 400, scale = 0.6)



C.5.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
  theme(legend.position = "bottom")

ggsave(filename = "Raw data/Trial/C.5.png", width = 30, height = 30, units = "cm", dpi = 400, scale = 0.6)



C.7.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
  theme(legend.position = "bottom")

ggsave(filename = "Raw data/Trial/C.7.png", width = 30, height = 30, units = "cm", dpi = 400, scale = 0.6)



C.14.totaldist %>%
  ggplot(aes(x= Trial, y = Total_distance)) +
  geom_jitter(aes(shape = Genotype), 
              size = 2
  ) +
  geom_boxplot(aes(fill = Trial),
               alpha = 0.25,
               outlier.shape = NA) +
  guides(fill = FALSE) +
  scale_fill_viridis_d(begin = 0.8, end = 0, option = "rocket") +
  scale_y_continuous(labels = comma, name = "Distance (mm)") +
  theme(legend.position = "bottom")

ggsave(filename = "Raw data/Trial/C.14.png", width = 30, height = 30, units = "cm", dpi = 400, scale = 0.6)


```



```{r distance mpsiiia binned}


p.A.5.binned <-
  A.5.fulldata %>%
  
  ggplot(aes(x = Genotype, y = Distance_travelled)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits= c(0,16000)) +
  scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 5 dpf") 





p.A.7.binned <-
  A.7.fulldata %>%
  
  ggplot(aes(x = Genotype, y = Distance_travelled)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits = c(0,16000)) +
  scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 7 dpf")

p.A.14.binned <-
  A.14.fulldata %>%
  
  ggplot(aes(x = Genotype, y = Distance_travelled)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits= c(0,16000)) +
  scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 14 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 


cowplot::plot_grid(
  cowplot::plot_grid(
    p.A.5.binned,
    
    p.A.7.binned,
    
    p.A.14.binned,
    align = "v",
    nrow = 3, 
    labels = "AUTO"
  ),
  cowplot::get_legend(
    A.5.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/20 minute bin/mpsiiia 20 min time bin.png", width = 30, height = 50, units = "cm", dpi = 400, scale = 0.6)




```

```{r mpsiii b distance binned}

p.B.5.binned <-
  B.5.fulldata %>%
  
  ggplot(aes(x = Genotype, y = Distance_travelled)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits= c(0,12000)) +
  scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIB 5 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))



p.B.7.binned <-
  B.7.fulldata %>%
  ggplot(aes(x = Genotype, y = Distance_travelled)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits= c(0,12000)) +
  scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIB 7 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 

p.B.14.binned <-
  B.14.fulldata %>%
    ggplot(aes(x = Genotype, y = Distance_travelled)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits= c(0,12000)) +
  scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
   ggtitle("MPS IIIB 14 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 



cowplot::plot_grid(
  cowplot::plot_grid(
    p.B.5.binned,
    
    p.B.7.binned,
    
    p.B.14.binned,
    align = "v",
    nrow = 3, 
    labels = "AUTO"
  ),
  cowplot::get_legend(
    B.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)


ggsave(filename = "Raw data/20 minute bin/mpsiiib 20 min time bin.png", width = 30, height = 50, units = "cm", dpi = 400, scale = 0.6)

```

```{r mpsiiic binned distance travelled}


p.C.5.binned <-
  C.5.fulldata %>%
    ggplot(aes(x = Genotype, y = Distance_travelled)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits= c(0,14000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
   ggtitle("MPS IIIC 5 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 


p.C.7.binned <-
  C.7.fulldata %>%
  ggplot(aes(x = Genotype, y = Distance_travelled)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits= c(0,14000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
   ggtitle("MPS IIIC 7 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 



p.C.14.binned <-
  C.14.fulldata %>%
    ggplot(aes(x = Genotype, y = Distance_travelled)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Distance (mm)", limits= c(0,14000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
   ggtitle("MPS IIIC 14 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 



cowplot::plot_grid(
  cowplot::plot_grid(
    p.C.5.binned,
    
    p.C.7.binned,
    
    p.C.14.binned,
    align = "v",
    nrow = 3, 
    labels = "AUTO"
  ),
  cowplot::get_legend(
    C.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/20 minute bin/mpsiiic 20 min time bin.png", width = 30, height = 50, units = "cm", dpi = 400, scale = 0.6)

```



```{r distance mpsiiia time moving}


p.A.5.movtime <-
  A.5.vel %>%
  
  ggplot(aes(x = Genotype, y = cum_movement)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits= c(0,1200), breaks = c(0, 300, 600, 900, 1200)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 5 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 



p.A.7.movtime <-
  A.7.vel %>%
  
  ggplot(aes(x = Genotype, y = cum_movement)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  #scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits = c(0,1200), breaks = c(0, 300, 600, 900, 1200)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 7 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 


p.A.14.movtime <-
  A.14.vel %>%
  
  ggplot(aes(x = Genotype, y = cum_movement)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits = c(0,1201), breaks = c(0, 300, 600, 900, 1200)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 14 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 



cowplot::plot_grid(
  cowplot::plot_grid(
    p.A.5.movtime,
    
    p.A.7.movtime,
    
    p.A.14.movtime,
    align = "v",
    nrow = 3, 
    labels = "AUTO"
  ),
  cowplot::get_legend(
    A.5.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Time moving/mpsiiia time moving.png", width = 30, height = 50, units = "cm", dpi = 400, scale = 0.6)


```

```{r distance mpsiiib time moving}


p.B.5.movtime <-
  B.5.vel %>%
  
  ggplot(aes(x = Genotype, y = cum_movement)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits= c(0,1200), breaks = c(0, 300, 600, 900, 1200)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIB 5 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 



p.B.7.movtime <-
  B.7.vel %>%
  
  ggplot(aes(x = Genotype, y = cum_movement)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  #scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits = c(0,1200), breaks = c(0, 300, 600, 900, 1200)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIB 7 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 


p.B.14.movtime <-
  B.14.vel %>%
  
  ggplot(aes(x = Genotype, y = cum_movement)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits = c(0,1201), breaks = c(0, 300, 600, 900, 1200)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIB 14 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 



cowplot::plot_grid(
  cowplot::plot_grid(
    p.B.5.movtime,
    
    p.B.7.movtime,
    
    p.B.14.movtime,
    align = "v",
    nrow = 3, 
    labels = "AUTO"
  ),
  cowplot::get_legend(
    B.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Time moving/mpsiiib time moving.png", width = 30, height = 50, units = "cm", dpi = 400, scale = 0.6)


```

```{r distance mpsiiia time moving}


p.C.5.movtime <-
  C.5.vel %>%
  
  ggplot(aes(x = Genotype, y = cum_movement)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits= c(0,1200), breaks = c(0, 300, 600, 900, 1200)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIC 5 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 



p.C.7.movtime <-
  C.7.vel %>%
  
  ggplot(aes(x = Genotype, y = cum_movement)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  #scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits = c(0,1200), breaks = c(0, 300, 600, 900, 1200)) +
  scale_x_discrete(name = "e ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIC 7 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 


p.C.14.movtime <-
  C.14.vel %>%
  
  ggplot(aes(x = Genotype, y = cum_movement)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits = c(0,1201), breaks = c(0, 300, 600, 900, 1200)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIC 14 dpf") +
  theme(legend.position = "none", plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1)) 



cowplot::plot_grid(
  cowplot::plot_grid(
    p.C.5.movtime,
    
    p.C.7.movtime,
    
    p.C.14.movtime,
    align = "v",
    nrow = 3, 
    labels = "AUTO"
  ),
  cowplot::get_legend(
    C.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Time moving/mpsiiic time moving.png", width = 30, height = 50, units = "cm", dpi = 400, scale = 0.6)


```



```{r active velocity mpsiiia }

p.A.5.vel <-
A.5.vel %>%
 ggplot(aes(x = Genotype, y = active_velocity)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Velocity (mm/s)", limits = c(0,14)) +  #, breaks= seq(0,12000, by=2000)) +
    scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 5 dpf") +
  theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))


p.A.7.vel <-
A.7.vel %>%
 ggplot(aes(x = Genotype, y = active_velocity)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Velocity (mm/s)", limits = c(0,14))+
  scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
    ggtitle("MPS IIIA 7 dpf") +
  theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))


 

p.A.14.vel <-
A.14.vel %>%
 ggplot(aes(x = Genotype, y = active_velocity)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  #scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Velocity (mm/s)", limits = c(0,14)) +  #, breaks= seq(0,12000, by=2000)) +
    scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 14 dpf") +
  theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))


cowplot::plot_grid(
  cowplot::plot_grid(
    p.A.5.vel,
  
    p.A.7.vel,
    
    p.A.14.vel,
    align = "v",
    nrow = 3
  ),
  cowplot::get_legend(
    A.5.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
        ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Active velocity/mpsiiia active velocity.png", width = 30, height = 50, units = "cm", dpi = 400, scale = .6)
```

```{r active velocity mps iiib}

p.B.5.vel <-
B.5.vel %>%
 ggplot(aes(x = Genotype, y = active_velocity)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Velocity (mm/s)", limits = c(-.1,16)) +  #, breaks= seq(0,12000, by=2000)) +
    scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIB 5 dpf") +
  theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))


p.B.7.vel <-
B.7.vel %>%
 ggplot(aes(x = Genotype, y = active_velocity)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Velocity (mm/s)", limits = c(-.1,16))+
  scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
    ggtitle("MPS IIIB 7 dpf") +
  theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))


 

p.B.14.vel <-
B.14.vel %>%
 ggplot(aes(x = Genotype, y = active_velocity)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  #scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Velocity (mm/s)", limits = c(-.1,16)) +  #, breaks= seq(0,12000, by=2000)) +
    scale_x_discrete( name = " ") + 
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIB 14 dpf") +
  theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))


cowplot::plot_grid(
  cowplot::plot_grid(
    p.B.5.vel,
  
    p.B.7.vel,
    
    p.B.14.vel,
    align = "v",
    nrow = 3
  ),
  cowplot::get_legend(
    B.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
        ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Active velocity/mpsiiib active velocity.png", width = 30, height = 50, units = "cm", dpi = 400, scale = .6)
```



```{r active velocity mpsiiic }

p.C.5.vel <-
C.5.vel %>%
 ggplot(aes(x = Genotype, y = active_velocity)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Velocity (mm/s)", limits = c(-.1,16)) +  #, breaks= seq(0,12000, by=2000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIC 5 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))


p.C.7.vel <-
C.7.vel %>%
 ggplot(aes(x = Genotype, y = active_velocity)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Velocity (mm/s)", limits = c(-.1,16)) +  #, breaks= seq(0,12000, by=2000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIC 7 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))



 

p.C.14.vel <-
  C.14.vel %>%
 ggplot(aes(x = Genotype, y = active_velocity)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Velocity (mm/s)", limits = c(-.1,16)) +  #, breaks= seq(0,12000, by=2000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIC 14 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))



cowplot::plot_grid(
  cowplot::plot_grid(
    p.C.5.vel,
    p.C.7.vel,
    p.C.14.vel,
    align = "v",
    nrow = 3
  ),
  cowplot::get_legend(
    C.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
        ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Active velocity/mpsiiic active velocity.png", width = 30, height = 50, units = "cm", dpi = 400, scale = .6)

```



```{r Time in centre zone mpsiia}

A.5.cen.time <-
  A.5.fulldata %>%
  ggplot(aes(x = Genotype, y = Time_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits = c(-.1,910)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 5 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))




A.7.cen.time <-
  A.7.fulldata %>%
  ggplot(aes(x = Genotype, y = Time_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  #scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits = c(-.1,910)) +  #, breaks= seq(0,12000, by=2000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin)+
  ggtitle("MPS IIIA 7 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))




A.14.cen.time <-
A.14.fulldata %>%
 ggplot(aes(x = Genotype, y = Time_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  #scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits = c(-.1,910)) +  #, breaks= seq(0,12000, by=2000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin)+
  ggtitle("MPS IIIA 14 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))






cowplot::plot_grid(
  cowplot::plot_grid(
    A.5.cen.time,
    A.7.cen.time,
    A.14.cen.time,
    align = "v",
    nrow = 3,
    labels = "AUTO"
  ),
  cowplot::get_legend(
    A.5.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Time in centre/mpsiiia time in centre.png", width = 30, height = 50, units = "cm", dpi = 400, scale = 0.6)


```

```{r time in centre mpsiiib}


B.5.cen.time <-
  B.5.fulldata %>%
   ggplot(aes(x = Genotype, y = Time_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)") +  #, breaks= seq(0,12000, by=2000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin)+
  ggtitle("MPS IIIB 5 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))






B.7.cen.time <-
  B.7.fulldata %>%
    ggplot(aes(x = Genotype, y = Time_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)") + 
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin)+
  ggtitle("MPS IIIB 7 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))



B.14.cen.time <-
B.14.fulldata %>%
    ggplot(aes(x = Genotype, y = Time_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)") +  #, breaks= seq(0,12000, by=2000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin)+
  ggtitle("MPS IIIB 14 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))


cowplot::plot_grid(
  cowplot::plot_grid(
    B.5.cen.time,
    
    B.7.cen.time,
    
    B.14.cen.time,
    align = "v",
    nrow = 3,
    labels = "AUTO"
  ),
  cowplot::get_legend(
    B.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Time in centre/mpsiiib time in centre.png", width = 30, height = 50, units = "cm", dpi = 400, scale = 0.6)


```

```{r time in centre mps iic}


C.5.cen.time <-
  C.5.fulldata %>%
  ggplot(aes(x = Genotype, y = Time_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  #scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)") +  #, breaks= seq(0,12000, by=2000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin)+
  ggtitle("MPS IIIC 5 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))




C.7.cen.time <-
  C.7.fulldata %>%
  ggplot(aes(x = Genotype, y = Time_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  #scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)", limits = c(-.1,600)) +  #, breaks= seq(0,12000, by=2000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin)+
  ggtitle("MPS IIIC 7 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))


C.14.cen.time <-
C.14.fulldata %>%
 ggplot(aes(x = Genotype, y = Time_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  #scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Time (s)") +  #, breaks= seq(0,12000, by=2000)) +
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIC 14 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))



cowplot::plot_grid(
  cowplot::plot_grid(
    C.5.cen.time,
  
    C.7.cen.time,
    
    C.14.cen.time,
    align = "v",
    nrow = 3
  ),
  cowplot::get_legend(
    C.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
        ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/Time in centre/mpsiiic time in centre.png", width = 30, height = 50, units = "cm", dpi = 400, scale = .6)


```




```{r frequency in centre mpsiiia}

p.A.5.freq <-
  A.5.fulldata %>%
 ggplot(aes(x = Genotype, y = Freq_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Number of crosses", limits = c(-1,250)) + 
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 5 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))



p.A.7.freq <-
  A.7.fulldata %>%
  ggplot(aes(x = Genotype, y = Freq_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Number of crosses", limits = c(-1,250)) + 
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 7 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))




p.A.14.freq <-
  A.14.fulldata %>%
  ggplot(aes(x = Genotype, y = Freq_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  A.col1 + A.col2 +
  scale_y_continuous(labels = comma, name = "Number of crosses", limits = c(-1,250)) + 
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIA 14 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))




cowplot::plot_grid(
  cowplot::plot_grid(
    p.A.5.freq,
    
    p.A.7.freq,
    
    p.A.14.freq,
    align = "v",
    nrow = 3, 
labels = "AUTO"  
),
  cowplot::get_legend(
    A.5.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/frequency centre/mpsiiia freq in centre.png", width = 30, height = 50, units = "cm", dpi = 400, scale = 0.6)



```

```{r frequency in centre mpsiiib}

p.B.5.freq <-
  B.5.fulldata %>%
 ggplot(aes(x = Genotype, y = Freq_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Number of crosses", limits = c(-1,180)) + 
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIB 5 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))


p.B.7.freq <-
  B.7.fulldata %>%
  ggplot(aes(x = Genotype, y = Freq_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Number of crosses", limits = c(-1,180)) + 
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPSIIIB 7 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))




p.B.14.freq <-
  B.14.fulldata %>%
  ggplot(aes(x = Genotype, y = Freq_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  B.col1 + B.col2 +
  scale_y_continuous(labels = comma, name = "Number of crosses", limits = c(-1,180)) + 
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIB 14 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))




cowplot::plot_grid(
  cowplot::plot_grid(
    p.B.5.freq,
    
    p.B.7.freq,
    
    p.B.14.freq,
    align = "v",
    nrow = 3, 
labels = "AUTO"  
),
  cowplot::get_legend(
    B.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/frequency centre/mpsiiib freq in centre.png", width = 30, height = 50, units = "cm", dpi = 400, scale = 0.6)



```

```{r frequency in centre mpsiiic}

p.C.5.freq <-
  C.5.fulldata %>%
 ggplot(aes(x = Genotype, y = Freq_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  scale_shape_manual(values= c(16,17,15,3,7,8,13)) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Number of crosses", limits = c(-1,320)) + 
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIC 5 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))


p.C.7.freq <-
  C.7.fulldata %>%
  ggplot(aes(x = Genotype, y = Freq_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Number of crosses", limits = c(-1,320)) + 
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIC 7 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))




p.C.14.freq <-
  C.14.fulldata %>%
  ggplot(aes(x = Genotype, y = Freq_in_centre)) +
  geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 2) +
  theme(legend.position = "none") +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA) +
  C.col1 + C.col2 +
  scale_y_continuous(labels = comma, name = "Number of crosses", limits = c(-1,320)) + 
  scale_x_discrete(name = " ") +
  theme(legend.position = "none") +
  facet_wrap(~Bin) +
  ggtitle("MPS IIIC 14 dpf") +
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.text.x = element_text(angle = 45, hjust=1))




cowplot::plot_grid(
  cowplot::plot_grid(
    p.C.5.freq,
    
    p.C.7.freq,
    
    p.C.14.freq,
    align = "v",
    nrow = 3, 
labels = "AUTO"  
),
  cowplot::get_legend(
    C.legtrial +
      theme(
        legend.position = c(0.5, 0.5),
        legend.direction = "horizontal")  
  ),
  nrow = 2,
  ncol = 1,
  rel_heights = c(25, 1)
)

ggsave(filename = "Raw data/frequency centre/mpsiiic freq in centre.png", width = 30, height = 50, units = "cm", dpi = 400, scale = 0.6)



```



