---
title: "hgsnat 7dpf"
author: "LR"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r library, include=FALSE}
# data manipulation
library(tidyverse)
library(magrittr)
library(readxl)

# statistical analysis
library(lme4)
library(broom)
library(car)
library(performance)
library(emmeans)
library(MASS)

# data visualstion
library(scales)
library(ggpubr)
library(ggeasy)
library(ggfortify)
library(ggbeeswarm)
library(kableExtra)
library(ggplate)

theme_set(theme_bw())
```




```{r joining data}

hgsnat <-
  read_excel("hgsnat 7dpf.xlsx") %>%
  subset(select = -c(`...1`,`Independent Variable Independent Variable Treatment`))
  
  hgsnat <-
  hgsnat %>%
  rename(
    "Trial" = `...2`,
    "Position" = `...3`,
    "Bin" = `...4`,
    "Distance_travelled" = "Distance moved center-point Total mm",
    "Mean_Velocity" = "Velocity center-point Mean mm/s",
    "Freq_in_centre" = "In zone Centre / center-point Frequency" ,
    "Time_in_centre" = "In zone Centre / center-point Cumulative Duration s",
    "cum_movement" = "Movement Moving / center-point Cumulative Duration s",
    "cum_stopping" = "Movement Not Moving / center-point Cumulative Duration s"
    ) %>%
    mutate(Bin = factor(Bin, levels = c("Start-0:20:00", "0:20:00-0:40:00", "0:40:00-1:00:00")),
       Trial = str_remove(Trial, pattern = "Trial     ") %>%
         as.factor())
  
  meta.hgsnat <-
  read_excel("Genotype 7dpf hgsnat.xlsx") %>%
  mutate(Genotype = factor(Genotype, levels = c('wt', 'het', 'hom')),
         Trial = as.factor(Trial),
         Position = as.factor(Position)
  )


hgsnat <-
  meta.hgsnat %>%
  left_join(hgsnat, by = c("Trial", "Position")) %>%
  subset(!(fish_id ==32)) %>%
  na.omit

#steve told me to change to m instead
#hgsnat.5 <-
 # hgsnat.5 %>%
  #dplyr::mutate(Distance_travelled = (Distance_travelled/1000))


```

```{r proportions}



totaldist.hgsnat <-
  hgsnat %>%
  group_by(fish_id) %>%
  mutate(Total_distance = sum(Distance_travelled)) %>%
  dplyr::select(fish_id, Trial, Position, Genotype, Total_distance, Freq_in_centre) %>%
  dplyr::distinct(Total_distance, .keep_all = TRUE) %>%
  ungroup() %>%
  droplevels()




geno.props.plot <- function(xaxis, input) {
  ggplot(data = input, aes(x = xaxis, fill = Genotype)) +
    geom_bar(mapping = aes(x = Genotype)) +
    scale_fill_viridis_d(option = "plasma",
                       end = 0.85)
}


geno.props.plot(input = totaldist.hgsnat, xaxis = "Genotype")


```


```{r exporting data}

totaldist.hgsnat %>% saveRDS("C.7.totaldist.rds")

totaldist.hgsnat %>%
  group_by(Genotype) %>%
  #dplyr::mutate(Total_dist = as.numeric(Total_dist)) %>%
  summarise(
    n = n(),
    mean = mean(Total_distance),
    median = median(Total_distance))

hgsnat %>% saveRDS("C.7.fulldata.rds")


```





Plotting overall distance travelled by genotype

```{r overall distance plot}
Cplotdistance <- function(dataset, Dependent){
  
 ggplot(data = dataset, aes(x = Genotype, y = Dependent)) +
    geom_jitter(aes(colour = Genotype,
                  shape = Trial),
              size = 4) +
  geom_boxplot(aes(fill = Genotype),
               alpha = 0.25,
               outlier.shape = NA
  ) +
  scale_fill_viridis_d(option = "plasma", end = 0.75) +
  scale_colour_viridis_d(option = "plasma", end = 0.75) +
    scale_y_continuous(labels = comma, name = "Distance (mm)") 

}




Cplotdistance(dataset = totaldist.hgsnat, Dependent = totaldist.hgsnat$Total_distance) +
  theme(text = element_text(size = 15))
#+
  #ggtitle("Total distance travelled in an hour (mm)")
  
ggsave(filename = "Total distance in an hour.png", width = 15, height = 10, units = "cm", dpi = 300, scale = 1.5)

  
  
Cplotdistance(dataset = hgsnat.5, Dependent = hgsnat.5$Distance_travelled) +
  facet_wrap(~Bin) +
  theme(text = element_text(size = 15))

ggsave(filename = "Distance per bin.png", width = 20, height = 10, units = "cm", dpi = 300, scale = 1.5)



```
