---
title: "1s 14dpf sgsh"
author: "LR"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library


```{r library, include=FALSE}
# data manipulation
library(tidyverse)
library(magrittr)
library(readxl)

# statistical analysis
library(lme4)
library(broom)
library(car)
library(performance)
library(emmeans)
library(MASS)

# data visualstion
library(scales)
library(ggpubr)
library(ggeasy)
library(ggfortify)
library(ggbeeswarm)
library(kableExtra)
library(ggplate)

theme_set(theme_bw())
```



```{r}
#stb stands for small timebin
stb.14.sgsh <-
  read_excel("tapping 1 second interval.xlsx")


stb.14.sgsh <-
  stb.14.sgsh %>%
  rename(
    "Trial" = `...2`,
    "Position" = `...3`,
    "Bin" = `...4`,
    "Distance_travelled" = "Distance moved center-point Total mm",
    "Mean_Velocity" = "Velocity center-point Mean mm/s",
    "Freq_in_centre" = "In zone Centre / center-point Frequency" ,
    "Time_in_centre" = "In zone Centre / center-point Cumulative Duration s",
    "cum_movement" = "Movement Moving / center-point Cumulative Duration s",
    "cum_stopping" = "Movement Not Moving / center-point Cumulative Duration s"
    ) %>%
       mutate(Trial = str_remove(Trial, pattern = "Trial     ") %>%
         as.factor())
```


 
```{r joining}
stb.14.sgsh<- 
  stb.14.sgsh %>%
  mutate(Bin = factor(Bin, levels = unique(Bin)))

```



setting up the meta file and working it into the data.stb file 

```{r}

stb.14.sgsh <-
  meta.sgsh.14 %>%
  left_join(stb.14.sgsh, by = c("Trial", "Position")) %>%
  na.omit


#Omiting data due to bad tracking or empty wells
stb.14.sgsh <- 
stb.14.sgsh %>%
  subset(!(Trial==1 & Position=="A3") &
         !(Trial==1 & Position=="B1") & 
         !(Trial==1 & Position=="C1") &
         !(Trial==1 & Position=="C2") &
         !(Trial==1 & Position=='D4') &
         !(Trial==2 & Position=='A3') &
         !(Trial==2 & Position=="B4") &
         !(Trial==2 & Position=="D2") &
         !(Trial==5 & Position=="D2") &
         !(Trial==5 & Position=="C3") &
         !(Trial==5 & Position=="A6") &
         !(Trial==5 & Position=="D4"))

```




#Velocity data 


just checking for some issues in tracking
```{r velocity check}

plotVelocity <- 
  function(input, dependent, independent){
  ggplot(data = input, aes(x = independent, y = dependent)) +
  geom_line(aes(group = Genotype))
  }

    
plotVelocity(input = stb.14.sgsh, dependent = stb.14.sgsh$Mean_Velocity, independent = stb.14.sgsh$Bin) 
  


```


```{r Bin number}
bin <- 
  stb.14.sgsh%>%
  dplyr::select(Bin) %>%
  unique() %>%
  as_tibble %>%
  set_colnames("Bin") %>%
  mutate(Bin_number = rownames(.))

bin$Bin_number <- as.numeric(bin$Bin_number) 


stb.14.sgsh <- bin %>%
  right_join(stb.14.sgsh, by = "Bin")
```
  
BOTH VELOCITY AND DISTANCE HAVE SAME DATA WHICH MEANS THE MACHINE'S OUTPUT IS JUST Distance/1 lmao. 
```{r ggplot}


stb.14.sgsh %>%
ggplot(aes(x = Bin_number, y = Mean_Velocity)) +
    geom_jitter(aes(colour = Genotype),
                alpha = 0.25,
              size = 2) +
  
  geom_smooth(aes(group = Genotype,
                  colour = Genotype)) +
  scale_fill_viridis_d(option = "inferno", end = .8) +
  scale_colour_viridis_d(option = "inferno", end = .8) +
    coord_cartesian(ylim = c(0,10)) +
  scale_y_continuous(labels = comma, name = "Velocity mm/s") +
  scale_x_continuous(name = "Velocity per second",
                     (breaks = seq(0, 3600, by = 600))) +
  ggtitle("14dpf sgsh velocity") +
  facet_wrap(~Trial) 


ggsave(filename = "velocity 1s.png", width = 30, height = 15, units = "cm", dpi = 600, scale = 1)

  
```



```{r ggplot distance}


stb.14.sgsh %>%
ggplot(aes(x = Bin_number, y = Distance_travelled)) +
    geom_jitter(aes(colour = Genotype),
                alpha = 0.25,
              size = 2) +
  
  geom_smooth(aes(group = Genotype,
                  colour = Genotype)) +
  scale_fill_viridis_d(option = "inferno", end = .8) +
  scale_colour_viridis_d(option = "inferno", end = .8) +
    coord_cartesian(ylim = c(0,10)) +
  scale_y_continuous(labels = comma, name = "Distance mm") +
  scale_x_continuous(name = "Distance every second",
                     (breaks = seq(0, 3600, by = 600))) +
  ggtitle("14dpf sgsh distance") +
  facet_wrap(~Trial) 


ggsave(filename = "Distance 1s.png", width = 30, height = 15, units = "cm", dpi = 600, scale = 1)

  
```


```{r}
stb.14.sgsh %>%
  group_by(fish_id) %>%
 filter(Bin_number %in% 1150:1250) %>%
ggplot(aes(x = Bin_number, y = Distance_travelled)) +
    geom_jitter(aes(colour = Genotype),
                alpha = 0.25,
              size = 2) +
  
  geom_smooth(aes(group = Genotype,
                  colour = Genotype)) +
  scale_fill_viridis_d(option = "inferno", end = .8) +
  scale_colour_viridis_d(option = "inferno", end = .8) +
    coord_cartesian(ylim = c(0,10)) +
  scale_y_continuous(labels = comma, name = "Distance mm") +
  scale_x_continuous(name = "Distance every second") +
  ggtitle("14dpf sgsh distance") +
  facet_wrap(~Trial)
  


ggsave(filename = "", width = 30, height = 15, units = "cm", dpi = 600, scale = 1)

  




```
